<?php

namespace Jazzee\CommonBundle\Entity;

use \Jazzee\CommonBundle\Entity\Program;
use IC\Bundle\Base\TestBundle\Test\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-21 at 12:11:45.
 */
class ProgramTest extends TestCase
{

    /**
     * @var Program
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new Program;
    }

    public function testDefaults()
    {
        $this->assertNull($this->object->getId());
        $this->assertNull($this->object->getName());
        $this->assertNull($this->object->getShortName());
        $this->assertFalse($this->object->isExpired());
    }

    /**
    * @covers \Jazzee\CommonBundle\Entity\Program::getId
    */
    public function testGetId()
    {
        $expected = rand(1, 100);
        $this->setPropertyOnObject($this->object, 'id', $expected);
        $this->assertSame($expected, $this->object->getId());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::getName
     */
    public function testGetName()
    {
        $expected = 'name' . uniqid();
        $this->setPropertyOnObject($this->object, 'name', $expected);
        $this->assertSame($expected, $this->object->getName());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::getShortName
     */
    public function testGetShortName()
    {
        $expected = 'shortname' . uniqid();
        $this->setPropertyOnObject($this->object, 'shortName', $expected);
        $this->assertSame($expected, $this->object->getShortName());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::setName
     */
    public function testSetName()
    {
        $expected = 'name' . uniqid();
        $this->object->setName($expected);
        $this->assertSame($expected, $this->object->getName());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::setShortName
     */
    public function testSetShortName()
    {
        $expected = 'name' . uniqid();
        $this->object->setShortName($expected);
        $this->assertSame($expected, $this->object->getShortName());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::expire
     */
    public function testExpire()
    {
        $this->assertFalse($this->object->isExpired());
        $this->object->expire();
        $this->assertTrue($this->object->isExpired());
        $this->object->unExpire();
        $this->assertFalse($this->object->isExpired());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::unExpire
     */
    public function testUnExpire()
    {
        $this->object->expire();
        $this->assertTrue($this->object->isExpired());
        $this->object->unExpire();
        $this->assertFalse($this->object->isExpired());
    }

    /**
     * @covers Jazzee\CommonBundle\Entity\Program::isExpired
     */
    public function testIsExpired()
    {
        $this->setPropertyOnObject($this->object, 'isExpired', true);
        $this->assertTrue($this->object->isExpired());
        $this->setPropertyOnObject($this->object, 'isExpired', false);
        $this->assertFalse($this->object->isExpired());
    }
}
