Jazzee\CommonBundle\Entity\CronVariable:
    type: entity
    table: cron_variables
    uniqueConstraints:
        cronvariable_name:
            columns:
                - name
    fields:
        id:
            id: true
            type: bigint
            generator: { strategy: AUTO }
        name:
            type: string
        value:
            type: text
