Jazzee\CommonBundle\Entity\ElementType:
    type: entity
    table: element_types
    uniqueConstraints:
        elementtype_class:
            columns:
                - class
        elementtype_name:
            columns:
                - name
    fields:
        id:
            id: true
            type: bigint
            generator: { strategy: AUTO }
        name:
            type: string
        class:
            type: string
