Jazzee\CommonBundle\Entity\PageType:
    type: entity
    table: page_types
    uniqueConstraints:
        pagetype_bundleName:
            columns:
                - bundleName
        pagetype_name:
            columns:
                - name
    fields:
        id:
            id: true
            type: bigint
            generator: { strategy: AUTO }
        name:
            type: string
        bundleName:
            type: string
        routeLoaderService:
            type: string
