Jazzee\CommonBundle\Entity\PaymentVariable:
    type: entity
    table: payment_variables
    uniqueConstraints:
        payment_variable_name:
            columns:
                - payment_id
                - name
    fields:
        id:
            id: true
            type: bigint
            generator: { strategy: AUTO }
        name:
            type: string
        value:
            type: text
    manyToOne:
        payment:
            targetEntity: \Jazzee\CommonBundle\Entity\Payment
            inversedBy: variables
            joinColumns:
                payment_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
