Jazzee\CommonBundle\Entity\School:
    type: entity
    table: schools
    repositoryClass: \Jazzee\CommonBundle\Repository\School
    fields:
        id:
            id: true
            type: bigint
            generator: { strategy: AUTO }
        name:
            type: string
            length: 255
            unique: true
        searchTerms:
            type: text
            nullable: true
        state:
            type: string
            length: 64
            nullable: true
        city:
            type: string
            length: 64
            nullable: true
        postalCode:
            type: string
            length: 64
            nullable: true
        country:
            type: string
            length: 128
            nullable: true
        code:
            type: string
