Jazzee\CommonBundle\Entity\Tag:
    type: entity
    table: tags
    repositoryClass: \Jazzee\CommonBundle\Repository\Tag
    uniqueConstraints:
        tag_title:
            columns:
                - title
    fields:
        id:
            id: true
            type: bigint
            generator: { strategy: AUTO }
        title:
            type: string
    manyToMany:
        applicants:
            targetEntity: \Jazzee\CommonBundle\Entity\Applicant
            mappedBy: tags
            joinTable: {  }
            orderBy: null
